name: hyperparam_example
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - numpy
    - click
    - pandas
    - scipy
    - scikit-learn
    - tensorflow==1.13.1
    - matplotlib
    - keras==2.3.1
    - mlflow>=1.6
    - hyperopt
    - protobuf<4.0.0
